INSERT INTO system_connections(
    system_key,
    display_name,
    base_url,
    status,
    capabilities_json,
    details_json
) VALUES
    (
        'wechat-search',
        '微信搜一搜',
        'http://127.0.0.1:8765',
        'unknown',
        '["read","keyword_refresh","batch_refresh","history_import"]',
        '{"source_kind":"legacy_http_sqlite_markdown"}'
    ),
    (
        'wechat-mp',
        '公众号监控',
        'http://127.0.0.1:28765',
        'unknown',
        '["read","login_check","account_refresh","markdown_import"]',
        '{"source_kind":"legacy_http_markdown"}'
    ),
    (
        'xhs-search',
        '小红书关键词监控',
        'http://127.0.0.1:8766',
        'unknown',
        '["read","keyword_refresh","batch_refresh","history_import"]',
        '{"source_kind":"legacy_http_json"}'
    ),
    (
        'geopromax',
        'GEOProMax',
        'http://127.0.0.1:8790',
        'unknown',
        '["read","json_import","manual_paid_refresh","history_import"]',
        '{"source_kind":"legacy_http_sqlite_json_markdown"}'
    ),
    (
        'wiki',
        'Wiki / 母文章库',
        'http://127.0.0.1:18923',
        'unknown',
        '["read","search","edit","reindex","ocr"]',
        '{"source_kind":"legacy_http_markdown"}'
    ),
    (
        'writing-money',
        'WritingMoney',
        NULL,
        'unknown',
        '["project_create","material_select","batch_generate"]',
        '{"source_kind":"static_demo_to_be_reimplemented"}'
    ),
    (
        'publishing',
        '旧写作与发布',
        NULL,
        'unknown',
        '["preview","dry_run","draft","publish_with_confirmation"]',
        '{"source_kind":"legacy_local_code"}'
    );
