-- 微信关键词迁移第一阶段：为全部 HTTP 操作登记独立、可审计的迁移开关。
-- 读操作保留 legacy 作为安全默认；写入/外部动作固定在 Hub 侧，不能由开关导向旧真实源。
INSERT INTO migration_switches(
    switch_id, module_key, contract_key, data_mode, enabled, rollback_mode,
    updated_at, updated_by, reason
) VALUES
    ('sw_wechat_001', 'wechat-search', 'monitor-data', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_002', 'wechat-search', 'bootstrap', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_003', 'wechat-search', 'keyword', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_004', 'wechat-search', 'account', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_005', 'wechat-search', 'article-content', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_006', 'wechat-search', 'article-hit-detail', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_007', 'wechat-search', 'keyword-manage', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_008', 'wechat-search', 'keyword-discovery', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_009', 'wechat-search', 'refresh-status', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_010', 'wechat-search', 'refresh-all-status', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_011', 'wechat-search', 'refresh-all-history', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_012', 'wechat-search', 'scheduler-status', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_013', 'wechat-search', 'articles', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_014', 'wechat-search', 'articles-accounts', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_015', 'wechat-search', 'agent-manifest', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_016', 'wechat-search', 'agent-daily-brief', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_017', 'wechat-search', 'agent-metric-dictionary', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_018', 'wechat-search', 'agent-evidence', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_019', 'wechat-search', 'penalty-signals', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_020', 'wechat-search', 'account-aliases', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_021', 'wechat-search', 'article-cover-image', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段读接口安全默认'),
    ('sw_wechat_022', 'wechat-search', 'aidso-keyword-heat-get', 'legacy', 1, 'legacy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '第一阶段外部读操作保留旧契约'),
    ('sw_wechat_023', 'wechat-search', 'keywords-refresh', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_024', 'wechat-search', 'refresh-all-cancel', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_025', 'wechat-search', 'refresh-all', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_026', 'wechat-search', 'scheduler-config', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_027', 'wechat-search', 'scheduler-trigger', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_028', 'wechat-search', 'article-covers', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '外部动作只能由受控 Hub provider 执行'),
    ('sw_wechat_029', 'wechat-search', 'aidso-keyword-heat-post', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '外部动作只能由受控 Hub provider 执行'),
    ('sw_wechat_030', 'wechat-search', 'keyword-pin', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_031', 'wechat-search', 'keyword-unpin', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_032', 'wechat-search', 'keyword-topic', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_033', 'wechat-search', 'keyword-note', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_034', 'wechat-search', 'keyword-bucket', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_035', 'wechat-search', 'group-create', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_036', 'wechat-search', 'group-update', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_037', 'wechat-search', 'group-delete', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_038', 'wechat-search', 'keyword-create', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_039', 'wechat-search', 'keyword-update', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_040', 'wechat-search', 'keyword-archive', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_041', 'wechat-search', 'keyword-refresh-policy', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_042', 'wechat-search', 'keyword-commercial-value', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源'),
    ('sw_wechat_043', 'wechat-search', 'keyword-auto-archive-lock', 'hub', 1, 'hub', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'migration_0016', '写操作禁止切回旧真实源');
